# Item ID of the wand tool. Make sure this doesn't conflict with
# any other tools such as the WE edit tool
edit-tool: 280

# The maximum number of blocks that can be edited at once.
max-blocks: 100

# Delay in seconds
delay:

# Material prices
prices:
  obsidian: 50
  cobblestone: 30
  sand: 10