# Item ID of the wand tool. Make sure this doesn't conflict with
# any other tools such as the WE edit tool
edit-tool: 280

# The maximum number of blocks that can be edited at once.
max-blocks: 100

# Delay in seconds
delay: 10

# Material prices
prices:
  obsidian: 50
  cobblestone: 30
  sand: 10

# Message configuration
message:
  # When a player is a given an edit wand.
  wand-received: '&aEdit wand received.'

  # When the player attempts to make an edit without having enough money.
  not-enough-money: '&cNot enough money'

  # When the player attempts to use /gen without a complete cuboid selection.
  incomplete-selection: '&cYou must complete your selection first.'

  # When the player attempts to edit a chunk that isn't owned by their faction.
  attempt-unclaimed-edit: '&cOnly owners of this claim can edit.'

  # When /gen succeeds and all blocks have been placed.
  edit-success: '&aEdit successful.'

  # When the players cooldown is over.
  edit-available: '&eEdit wand ready.'

  # When the player is still on cooldown
  edit-unavailable: '&cYou must wait before using this again.'

  pos1-set: '&ePosition 1 set.'
  pos2-set: '&ePosition 2 set.'
