name: GenWand
main: ttdev.genwand.GenWand
version: 1.0
author: [Tre, Thomas]
depends: [Vault, WorldEdit, API, Factions, MassiveCore]
commands:
  gw:
    description: View GenWand help menu.
    permission: genwand.use